(define (while? exp)
  (tagged-list? exp `while))
(define (while-predicate exp)
  (cadr exp))
(define (while-body exp)
  (caddr exp))
(define (whiel->combination exp)
  (make-if (while-predicate exp)
	   (sequence->exp (while-body exp)))
